version: '3'

vars:
  PLATFORM: sulfone
  SERVICE: boron
  USER: kirinnee/
  REGISTRY_HOST: http://host.docker.internal:9001

includes:
  docker: tasks/Taskfile.docker.yaml
  general:
    taskfile: tasks/Taskfile.tf.yaml
    dir: tofu/live/general
  ruby:
    taskfile: tasks/Taskfile.tf.yaml
    dir: tofu/live/ruby
  opal:
    taskfile: tasks/Taskfile.tf.yaml
    dir: tofu/live/opal
  mica:
    taskfile: tasks/Taskfile.tf.yaml
    dir: tofu/live/mica
  talc:
    taskfile: tasks/Taskfile.tf.yaml
    dir: tofu/live/talc

tasks:
  setup:
    desc: 'Setup the repository'
    cmds:
      - go mod tidy
      - ./scripts/local/secrets.sh
  provision-and-deploy:
    desc: 'Provision and deploy the cluster'
    cmds:
      - ./scripts/cd/provision-and-deploy.sh
  exec:
    desc: 'SSH into the executor'
    cmds:
      - ./scripts/local/exec.sh
  build:
    desc: 'Build the binary'
    cmds:
      - go build -o bin/{{.PLATFORM}}-{{.SERVICE}} .
  run:
    desc: 'Run the application'
    cmds:
      - go run . {{.CLI_ARGS}}
